export const ROOT_STACK = {
  MAIN_APP: 'MAIN_APP',
  GLOBAL_ALERT: 'GLOBAL_ALERT',
  GLOBAL_CONFIRM: 'GLOBAL_CONFIRM',
}

export const SCREEN_ROUTER = {
  MAIN: 'MAIN',
  AUTH: 'AUTH',
  SPLASH: 'SPLASH',
}

export const MAIN_TAB = {
  HOME: 'HOME',
  OTHER: 'OTHER',
  CALENDAR: 'CALENDAR',
  ACCOUNT: 'ACCOUNT',
}

export const SCREEN_ROUTER_AUTH = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  //   PASSWORD: 'PASSWORD',
}

export const SCREEN_ROUTER_APP = {
  CHAT: 'CHAT',
}
